[package]
name = "rustbridge"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "dylib"]

[dependencies]
lazy_static = "1.4.0"
serde = { version = "1.0.194", features = ["derive"] }
serde_json = "1.0.111"
tokio = { version = "1.35.1", features = ["full"] }
