name: e2e tests for RustyCalc
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'app/**'
      - '.github/workflows/e2e-tests.yml'
jobs:
  build:
    name: Install and do e2e test
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: yarn
          cache-dependency-path: '**/yarn.lock'
          lfs: 'true'

      - name: Set LANG globally for subsequent steps
        run: echo "LANG=en_US.UTF-8" >> $GITHUB_ENV

      - name: Install detox cli
        run: npm install -g detox-cli

      - name: Checkout 
        uses: actions/checkout@v4
        with: 
          lfs: 'true'

      - name: Setup
        working-directory: app/packages/calc
        run: bash -c "yarn setup"

      - name: Pod install for iOS
        working-directory: app/packages/calc/ios
        run: npx pod-install

      - name: Detox build for iOS
        working-directory: app/packages/calc
        run: bash -c "detox build -c ios.release" > /dev/null

      - name: Detox e2e tests for iOS
        working-directory: app/packages/calc
        run: bash -c "NODE_OPTIONS='--max-old-space-size=4096' detox test -c ios.release"

      - name: Create the required Android emulator
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-31;google_apis;arm64-v8a"
          $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager --verbose create avd --force --name "pixel_4" --device "pixel_4" --package "system-images;android-31;google_apis;arm64-v8a"
        env:
          ANDROID_HOME=${{ env.ANDROID_HOME }}

      - name: Detox build for Android
        working-directory: app/packages/calc
        run: bash -c "detox build -c android.release" > /dev/null

      - name: Detox e2e tests for Android
        working-directory: app/packages/calc
        run: bash -c "NODE_OPTIONS='--max-old-space-size=4096' detox test -c android.release"
