name: EAS / Release / Expo Update
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/workflows/eas.release.update.main.yml'
jobs:
  build:
    name: Checkout and EAS Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - name: Install dependencies
        working-directory: app/packages/calc
        run: yarn install

      - name: Run setup
        working-directory: app/packages/calc
        run: yarn setup

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Perform eas update
        working-directory: app/packages/calc
        run: eas update --channel=production --message="$(git log -1 --pretty=%B)"
