name: EAS / Release / Expo Update
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - mobile-release-expo-update

jobs:
  build:
    name: Checkout and EAS Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - name: Print branch name
        run: echo ${GITHUB_REF_NAME}

      - name: Install dependencies
        working-directory: app/packages/calc
        run: yarn install

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Print branch name
        run: echo ${{ github.ref_name }}

      - name: Perform eas update (main)
        if:  github.ref_name == 'main'
        working-directory: app/packages/calc
        run: echo "Running eas update for main branch" #eas update --channel=production --message="$(git log -1 --pretty=%B)"

      - name: Perform eas update (mobile-release-expo-update)
        if: github.ref_name  == 'mobile-release-expo-update'
        working-directory: app/packages/calc
        run: echo "Running eas update for mobile-release-expo-update branch" #eas update --channel=production --message="$(git log -1 --pretty=%B)"
